# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Run tests
        run: |
          bazel test //...

      - name: Build binaries
        run: |
          bazel build //snapshots/go/cmd/snapshots:snapshots
          bazel run //tools:release -- ${{ github.ref_name }} ${{ github.workspace }}

      - name: Prepare workspace snippet
        run: |
          bash .github/scripts/workplace-snippet.sh ${{ github.ref_name }} > release-notes.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          body_path: release-notes.txt
          files: |
            ${{ github.workspace }}/bazel-snapshots-${{ github.ref_name }}/*
