# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Run tests
        run: |
          bazel test //...

      - name: Build linux-amd64
        run: |
          bazel build //snapshots/go/cmd/snapshots:snapshots-linux-amd64
          mv bazel-bin/snapshots/go/cmd/snapshots/snapshots_/snapshots bazel-bin/snapshots-linux-amd64

# Fails. Have to find out why.
#      - name: Build darwin-amd64
#        run: |
#          bazel build //snapshots/go/cmd/snapshots:snapshots-darwin-amd64
#          mv bazel-bin/snapshots/go/cmd/snapshots/snapshots_/snapshots bazel-bin/snapshots-darwin-amd64

      - name: Prepare workspace snippet
        run: |
          bash .github/scripts/workplace-snippet.sh ${{ env.GITHUB_REF_NAME }} > release-notes.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body_path: release-notes.txt
          files: |
            bazel-bin/snapshots-*